version: '3.8'
services:
  symfony-test-caddy:
    container_name: symfony-test-caddy-dev
    image: caddy:2.2.1-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: "no"
    ports:
      - "8089:80"

  symfony-test-postgres:
    container_name: symfony-test-postgres-dev
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      - DEBUG=false
      - DB_USER=test-dev
      - DB_PASS=test-dev
      - DB_NAME=postgres,test_dev
    ports:
      - "5440:5432"

  symfony-test-core:
    container_name: symfony-test-core-dev
    build: .
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./:/srv
    env_file:
      - .env
    restart: always
    ports:
      - "8081:80"

  symfony-pg-admin:
    container_name: symfony-test-pgadmin-dev
    image: zhajor/docker-phppgadmin
    ports:
      - "5441:80"
    environment:
      - DB_HOST=symfony-test-postgres
      - DB_PORT=5432

